name: Create release

on:
  push:
    tags:
      - piler*

env:
  IMAGE_NAME: sutoj/piler

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        arch: ['amd64','arm64']

    runs-on:
      - self-hosted
      - ${{ matrix.arch }}

    outputs:
      IMAGE_TAG: ${{ steps.get-version.outputs.IMAGE_TAG }}
      COMMIT_ID: ${{ steps.get-version.outputs.COMMIT_ID }}
      VERSION: ${{ steps.get-version.outputs.VERSION }}
      PACKAGE: ${{ steps.build-package.outputs.PACKAGE }}

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get-version
        uses: ./.github/actions/version

      - name: Build package
        id: build-package
        uses: ./.github/actions/build/package
        with:
          ARCH: ${{ matrix.arch }}
          COMMIT_ID: ${{ steps.get-version.outputs.COMMIT_ID }}
          DISTRO: 'jammy'
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          PROJECT_ID: 'piler'
          VERSION: ${{ steps.get-version.outputs.VERSION }}

      - name: Build image
        uses: ./.github/actions/build/image
        with:
          ARCH: ${{ matrix.arch }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          LOAD: false
          PACKAGE: ${{ steps.build-package.outputs.PACKAGE }}
          PUSH: true
          TEST_TAG: ${{ steps.get-version.outputs.VERSION }}

  create-release:
    needs:
      - build
      
    runs-on:
      - self-hosted
      - X64

    steps:
      - name: Create docker manifest
        run: |
          set -x
          docker manifest rm ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.VERSION }} || true
          docker manifest create ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.VERSION }} --amend ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.VERSION }}-amd64 --amend ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.VERSION }}-arm64
          docker manifest push ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.VERSION }}
        shell: bash

      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#*-}" \
              --generate-notes
          gh release upload "$tag" piler*deb
