name: Create release

on:
  push:
    tags:
      - piler*

env:
  IMAGE_NAME: sutoj/piler
  TEST_TAG: test

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        arch: ['ARM64']

    runs-on:
      - self-hosted
      - ${{ matrix.arch }}

    outputs:
      IMAGE_TAG: ${{ steps.get-version.outputs.IMAGE_TAG }}
      COMMIT_ID: ${{ steps.get-version.outputs.COMMIT_ID }}
      VERSION: ${{ steps.get-version.outputs.VERSION }}
      PACKAGE: ${{ steps.build-package.outputs.PACKAGE }}

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get-version
        uses: ./.github/actions/version

      - name: Build package
        id: build-package
        uses: ./.github/actions/build/package
        with:
          ARCH: ${{ matrix.arch }}
          COMMIT_ID: ${{ steps.get-version.outputs.COMMIT_ID }}
          DISTRO: ${{ env.DISTRO }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          PROJECT_ID: ${{ env.PROJECT_ID }}
          TEST_TAG: ${{ env.TEST_TAG }}
          VERSION: ${{ steps.get-version.outputs.VERSION }}

       # TODO: build and publish images


  create-release:
    needs:
      - build
      
    runs-on:
      - self-hosted
      - X64

    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: package-*
          merge-multiple: true

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#*-}" \
              --generate-notes
          gh release upload "$tag" piler*deb
